WIP: Normalize molecule infrastructure
openstack-k8s-operators/edpm-ansible pull request #171
Opened 2023-05-26 09:49 UTC by Deydra71

Create basic structure for generating molecule tests.

2023-07-13 08:10 UTC, Deydra71 commented
Currently correcting the generation of prepare.yml files, as the tests are failing due to the change of the path of test_deps.

2023-07-14 06:18 UTC, Deydra71 commented
recheck

2023-07-14 06:18 UTC, Deydra71 commented
recheck

2023-07-14 07:52 UTC, Deydra71 commented
recheck

2023-07-19 07:51 UTC, jpodivin requested changes
It's mostly great. Apart from the few things in the script, I think it would be a good idea to write some comments there as well.

2023-07-19 07:51 UTC, jpodivin commented on scripts/generate_molecule.py
> +template_path = "molecule/common"
Constants should be in upper case.

2023-07-19 07:51 UTC, jpodivin commented on scripts/generate_molecule.py
> +            if 'Prepare test_deps' in existing_prepare_content or 'role: ../../../../molecule/common/test_deps' in existing_prepare_content:
The later string could be factored out as constant to improve readability.

2023-07-19 16:17 UTC, Deydra71 commented
recheck

2023-07-20 06:19 UTC, Deydra71 commented
recheck

2023-07-20 07:29 UTC, Deydra71 commented
recheck

2023-07-25 06:47 UTC, Deydra71 commented
recheck

2023-07-26 09:33 UTC, Deydra71 commented
recheck

On Tue, 25 Jul 2023 at 17:33, softwarefactory-project-zuul[bot] <
***@***.***> wrote:

> Build failed (check pipeline). For information on how to proceed, see
> http://docs.openstack.org/infra/manual/developers.html#automated-testing
>
>
> https://review.rdoproject.org/zuul/buildset/95112484286e459380f8ee22c24b3446
>
> ✔️ edpm-ansible-molecule-edpm-podman
> <https://review.rdoproject.org/zuul/build/053acf0b92ca413da6b3ea00d969e8da>
> SUCCESS in 5m 25s
> ✔️ edpm-ansible-molecule-edpm-module_load
> <https://review.rdoproject.org/zuul/build/a0c94769e8e7403cb8c88befdc7355fe>
> SUCCESS in 5m 08s
> ✔️ edpm-ansible-molecule-edpm-kernel
> <https://review.rdoproject.org/zuul/build/b087b879129540fe95b3bdc1cb0148cb>
> SUCCESS in 11m 13s
> ✔️ edpm-ansible-content-provider
> <https://review.rdoproject.org/zuul/build/e2698d82e8bb49c5b25db0dcf6b27fd2>
> SUCCESS in 1h 21m 13s
> ❌ edpm-ansible-crc-podified-edpm-deployment
> <https://review.rdoproject.org/zuul/build/0dd33f173291430f82089247fdc00937>
> *FAILURE* in 19m 49s
> ✔️ edpm-ansible-crc-podified-edpm-baremetal
> <https://review.rdoproject.org/zuul/build/0096a9088a844026bee8f20b5f62b1cd>
> SUCCESS in 1h 08m 49s
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openstack-k8s-operators/edpm-ansible/pull/171#issuecomment-1650067749>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX5IYSMPFJ376N4JBFE22DDXR7RK7ANCNFSM6AAAAAAYP727KM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-27 06:31 UTC, Deydra71 commented
recheck

On Wed, Jul 26, 2023, 11:51 AM softwarefactory-project-zuul[bot] <
***@***.***> wrote:

> Build failed (check pipeline). For information on how to proceed, see
> http://docs.openstack.org/infra/manual/developers.html#automated-testing
>
>
> https://review.rdoproject.org/zuul/buildset/2995dc8ad4614b76a33392273d01e01a
>
> ✔️ edpm-ansible-molecule-edpm-podman
> <https://review.rdoproject.org/zuul/build/05deea215db849fa97c0319107673a21>
> SUCCESS in 15m 09s
> ✔️ edpm-ansible-molecule-edpm-module_load
> <https://review.rdoproject.org/zuul/build/b182b8b375ea4812a897113e75e4aa69>
> SUCCESS in 4m 46s
> ✔️ edpm-ansible-molecule-edpm-kernel
> <https://review.rdoproject.org/zuul/build/f6efb0c7de8e4edfbe717528019c89d4>
> SUCCESS in 12m 32s
> ❌ edpm-ansible-content-provider
> <https://review.rdoproject.org/zuul/build/9822586a27024f0e88fc33a8eb12ae13>
> *FAILURE* in 8m 36s
> ⚠️ edpm-ansible-crc-podified-edpm-deployment
> <https://review.rdoproject.org/zuul/build/4f8bf2485b3b40b593054e5a39e3317a>
> SKIPPED Skipped due to failed job edpm-ansible-content-provider
> ⚠️ edpm-ansible-crc-podified-edpm-baremetal
> <https://review.rdoproject.org/zuul/build/418f5227582a46c09939e04fbc1f8c9d>
> SKIPPED Skipped due to failed job edpm-ansible-content-provider
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openstack-k8s-operators/edpm-ansible/pull/171#issuecomment-1651402498>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX5IYSMGIZY3AQUOEJFXDQTXSDSCNANCNFSM6AAAAAAYP727KM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-31 10:01 UTC, danpawlik commented
recheck

2023-07-31 10:09 UTC, danpawlik commented
recheck

2023-07-31 11:42 UTC, danpawlik commented
recheck

2023-08-01 14:59 UTC, danpawlik commented
recheck

2023-08-03 12:57 UTC, jpodivin approved these changes

2023-08-03 13:07 UTC, merged