Option to select the required DDP package
openstack-k8s-operators/edpm-ansible pull request #177
Opened 2023-06-02 08:40 UTC by Jaganathancse

This changes to provide the option to choose the required DDP package when multiple different packages are available.

2023-06-02 08:41 UTC, rabi commented
/ok-to-test

2023-06-02 14:16 UTC, rebtoor requested changes
I'd prefer to have a role with all these tasks integrated in an existing playbook or in a new one. It would give us more flexibility in using it.

Strictly speaking about the code, you should use FQCN for all used ansible modules.

2023-06-05 11:04 UTC, jpodivin requested changes
I believe `edpm_module_load` would be useful in this case. Also it may be for the best to turn other tasks into separate role of it's own, with properly exposed parameters, I assume similar installation procedure could be useful for other Intel drivers?

2023-06-06 11:14 UTC, slagle requested changes

2023-06-06 11:14 UTC, slagle commented on playbooks/deploy_edpm_kernel_ddp_pkg.yaml
I agree with the other comments that these tasks need to be added to an existing role, or a new role as opposed to a new playbook. EDPM consumes the roles, not the playbooks.

2023-07-04 20:24 UTC, Jaganathancse commented on playbooks/deploy_edpm_kernel_ddp_pkg.yaml
Ack

2023-07-07 08:19 UTC, rebtoor approved these changes

2023-07-07 08:31 UTC, merged