Drop test_deps role
openstack-k8s-operators/edpm-ansible pull request #182
Opened 2023-06-07 13:27 UTC by raukadah

this role is already moved to ci-framework[1] and let'use it from there.

The existing one is outdated and breaking the existing zuul molecule job.

[1]. https://github.com/openstack-k8s-operators/ci-framework/tree/main/ci_framework/roles/test_deps
Signed-off-by: Chandan Kumar <raukadah@gmail.com>

2023-06-07 13:28 UTC, cjeanner approved these changes
yay! convergence - more convergence!

2023-06-07 13:40 UTC, cjeanner commented
Not that easy apparently - the container used for molecule doesn't seem to provide ci-framework roles, so test_deps isn't there, sooo... :crab:

2023-06-08 08:17 UTC, jpodivin requested changes
I don't really know about this. Moving all tests from github to rdo is, by itself, considerable change I'm not sure I would entirely embrace. But, and I feel this is more important, removing the role creates a dependency on ci-framework we don't really need here.

I've seen first hand where this can end up with tripleo ecosystem, where we had to make intertwined changes in multiple repos to address some CIX or another. And if we can spare ourselves that now, I think we should.

2023-06-08 16:21 UTC, slagle approved these changes

2023-06-09 07:34 UTC, raukadah commented on ci/playbooks/mol_role_symlink.yaml
> +    - name: Create symlink for ci-framework test_deps role
Done

2023-06-09 08:12 UTC, rebtoor approved these changes

2023-06-09 08:40 UTC, raukadah commented
recheck

2023-06-09 11:08 UTC, slagle approved these changes

2023-06-09 15:26 UTC, rebtoor commented
> We have already wired ci-framework in edpm-ansible via makefile. Since we are already running zuul molecule jobs by using ci-framework . So I am extending the same work with other molecule jobs and re-using the role from ci-framework.

> We know both projects are dependent, since we are using Zuul, we can test the changes together. I think that is not an issue here.

On this point I want to add my 2 cents.

I totally agree on remove test_deps from edpm-ansible for a couple of reason:

1. you already have an updated version of it on ci-framework
2. i don't like the idea of having a role used only for testing purposes distributed in the collection. I don't remember see anything similar elsewhere either.

BTW, I'd like to keep execute molecule tests without triggering ci-framework. It shouldn't become a requirement for molecule. edpm-ansible should be a consumer of ci-framework just like the other repos in the organization. 

Anyone should have the possibility of cloning this repo and launch `molecule test` in a role folder without external dependencies.

To overcome that, we are thinking to write a "common" prepare phase for all the scenarios, adapting the amazing work started by @Deydra71 on https://github.com/openstack-k8s-operators/edpm-ansible/pull/171, that will replace the test_deps repo without using external tools.

I hope and I guess (given ansible idempotence) that this will not collide with test_deps role in the ci-framework.

I'll tag the rest of DF team to ask for their point of view. @slagle @bshephar @rabi @kajinamit

2023-06-09 16:09 UTC, slagle requested changes
I agree we should be able to run "molecule test" without having to rely on dependencies from ci-framework. Can we hold off on dropping this until we have the replacement in place that @rebtoor proposes?

2023-06-09 16:33 UTC, rebtoor commented
/hold

2023-10-27 13:16 UTC, closed without merging