Argspecs for edpm_frr role
openstack-k8s-operators/edpm-ansible pull request #239
Opened 2023-07-26 10:17 UTC by jpodivin

2023-07-28 13:08 UTC, rebtoor requested changes
@jpodivin i try to gather info for some values, but it's far out of my knowledge here... i mentioned @luis5tb aksing for his help adding description to fields.

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
`description: Enable bgpd daemon`

https://docs.frrouting.org/en/latest/setup.html?highlight=daemons#daemons-configuration-file

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb can you provide a description for this?

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-07-28 13:08 UTC, rebtoor commented on roles/edpm_frr/meta/argument_specs.yml
> +        description: ''
@luis5tb as above :sweat_smile:

2023-08-01 09:07 UTC, jpodivin commented
recheck

2023-08-01 09:08 UTC, jpodivin commented
> @jpodivin i try to gather info for some values, but it's far out of my knowledge here... i mentioned @luis5tb aksing for his help adding description to fields.

If we don't get any feedback soon I would recommend merging this in it's current state, and filling the details later.

2023-08-03 07:28 UTC, jpodivin commented
recheck

2023-08-03 07:32 UTC, rebtoor approved these changes

2023-08-04 13:25 UTC, jpodivin commented
recheck

2023-08-07 08:24 UTC, jpodivin commented
recheck

2023-08-07 11:59 UTC, slagle approved these changes

2023-08-07 12:09 UTC, merged