Finalizing arspecs for edpm_bootstrap
openstack-k8s-operators/edpm-ansible pull request #245
Opened 2023-07-27 08:16 UTC by jpodivin

2023-07-27 13:47 UTC, jpodivin commented
recheck

2023-07-28 13:29 UTC, rebtoor requested changes

2023-07-28 13:29 UTC, rebtoor commented on roles/edpm_bootstrap/meta/argument_specs.yml
> +      edpm_bootstrap_swap_size_megabytes:
`description: Swap file size (in Megabytes)`

2023-07-28 13:29 UTC, rebtoor commented on roles/edpm_bootstrap/meta/argument_specs.yml
> +      edpm_bootstrap_swap_path:
`description: Swap file location`

2023-07-28 13:29 UTC, rebtoor commented on roles/edpm_bootstrap/meta/argument_specs.yml
> +      edpm_bootstrap_swap_partition_enabled:
`description: Enable swap partition instead of swap file`

2023-07-28 13:29 UTC, rebtoor commented on roles/edpm_bootstrap/meta/argument_specs.yml
> +      edpm_bootstrap_swap_partition_label:
`description: partition label used to search swap partition on disk`

2023-07-28 15:11 UTC, rebtoor approved these changes

2023-07-28 15:49 UTC, merged