Adding configure_ovn_bgp_agent playbook
openstack-k8s-operators/edpm-ansible pull request #259
Opened 2023-08-03 09:46 UTC by jpodivin

2023-08-03 16:26 UTC, rebtoor requested changes

2023-08-03 16:26 UTC, rebtoor commented on playbooks/configure_ovn_bgp_agent.yaml
> +        name: op.edpm.edpm_ovn_bgp_agent
`osp.edpm.edpm_ovn_bgp_agent`

2023-08-03 16:26 UTC, rebtoor commented on playbooks/configure_ovn_bgp_agent.yaml
> +      import_role:
`ansible.builtin.import_role`

2023-08-04 09:38 UTC, rebtoor approved these changes
as discussed in chat, let's import the playbook as is then, after verifying that everything is working, we will improve it.

2023-08-07 20:44 UTC, slagle approved these changes

2023-08-09 08:24 UTC, jpodivin commented
recheck

2023-08-11 08:20 UTC, merged