Adding install_frr playbook
openstack-k8s-operators/edpm-ansible pull request #260
Opened 2023-08-03 09:48 UTC by jpodivin

2023-08-03 16:25 UTC, rebtoor requested changes

2023-08-04 09:22 UTC, rebtoor approved these changes
as discussed in chat, let's import the playbook as is then, after verifying that everything is working, we will improve it.

2023-08-07 20:44 UTC, slagle approved these changes
/override rdoproject.org/github-check

2023-08-09 08:25 UTC, jpodivin commented
recheck

2023-08-09 14:19 UTC, jpodivin commented
/override rdoproject.org/github-check

2023-08-10 14:23 UTC, merged