Adding install_ovn_bgp_agent playbook
openstack-k8s-operators/edpm-ansible pull request #262
Opened 2023-08-03 10:21 UTC by jpodivin

2023-08-03 16:23 UTC, rebtoor requested changes

2023-08-03 16:23 UTC, rebtoor commented on playbooks/install_ovn_bgp_agent.yaml
> +      import_role:
`ansible.builtin.import_role`

2023-08-04 09:25 UTC, rebtoor approved these changes
as discussed in chat, let's import the playbook as is then, after verifying that everything is working, we will improve it.

2023-08-07 20:46 UTC, slagle approved these changes
/override rdoproject.org/github-check

2023-08-14 12:39 UTC, merged