Adding run_ovn_bgp_agent playbook
openstack-k8s-operators/edpm-ansible pull request #265
Opened 2023-08-03 11:32 UTC by jpodivin

2023-08-03 16:21 UTC, rebtoor requested changes

2023-08-03 16:21 UTC, rebtoor commented on playbooks/run_ovn_bgp_agent.yaml
> +      import_role:
`ansible.builtin.import_role`

2023-08-04 09:47 UTC, rebtoor approved these changes

2023-08-04 11:56 UTC, jpodivin commented
recheck

2023-08-07 20:47 UTC, slagle approved these changes
/override rdoproject.org/github-check

2023-08-07 20:56 UTC, merged