mova edpm-ansible-crc-podified-edpm-baremetal to github-manual
openstack-k8s-operators/edpm-ansible pull request #270
Opened 2023-08-04 16:02 UTC by SeanMooney

This change moves the edpm-ansible-crc-podified-edpm-baremetal
job to the manual pipeline until it can be fixed.

2023-08-07 05:42 UTC, raukadah commented
@SeanMooney Thank you for taking a look at the job. Based on the health of[ edpm baremetal job ](https://review.rdoproject.org/zuul/builds?job_name=edpm-ansible-crc-podified-edpm-baremetal&skip=0), there are few success. Can we move this job to non-voting instead of github-manual? By making it non-voting, it will give feedback to developer. But moving it to github-manual, it will be completely ignored.

2023-08-07 10:18 UTC, SeanMooney commented
My experience is most developers ignore non voting job unless they are working on the thing it's testing and most people on the edpm ansible repo are not working on ironic. That is why I didn't make it non voting. I think it would be better to keep it in manual until the job is stabilised to save for time.

2023-08-07 11:08 UTC, raukadah approved these changes
Thank you @SeanMooney , make sense. Added an issue in jira backlog to move the job back to voting once crc standalone work finishes.

2023-08-07 11:10 UTC, raukadah commented
recheck

2023-08-07 12:26 UTC, rebtoor approved these changes

2023-08-08 05:25 UTC, rabi requested changes
The issue should be fixed after https://github.com/openstack-k8s-operators/openstack-operator/pull/427

It's red as a result of us force merging PRs that break the job without understanding the failures.

2023-09-28 19:50 UTC, closed without merging

2023-09-28 19:56 UTC, rebtoor commented
I've closed this PR because the job has already been removed, and it will be re-added after proper testing.