Add github action for openstack-ansibleee-runner build
openstack-k8s-operators/edpm-ansible pull request #32
Opened 2023-02-08 11:21 UTC by bshewale

2023-02-08 17:40 UTC, rebtoor requested changes
Thanks a lot for this PR! I left a couple of comments for few minor tweaks.

2023-02-08 17:40 UTC, rebtoor commented on .github/workflows/openstack-ansibleee-runner.yaml
> +    name: Build openstack-ansibleee-operator image using buildah
`openstack-ansibleee-runner` image

2023-02-08 17:40 UTC, rebtoor commented on .github/workflows/openstack-ansibleee-runner.yaml
> +        run: echo "::set-output name=ok::true"
Github has deprecated `::set-output`, read [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

You can use `run: echo "ok=true" >> $GITHUB_OUTPUT`

2023-02-09 12:10 UTC, bshewale commented on .github/workflows/openstack-ansibleee-runner.yaml
> +    name: Build openstack-ansibleee-operator image using buildah
Done

2023-02-09 13:15 UTC, rebtoor approved these changes

2023-02-09 13:16 UTC, merged