Fix name of the config_src variable in neutron_sriov role
openstack-k8s-operators/edpm-ansible pull request #354
Opened 2023-09-20 12:25 UTC by slawqo

2023-09-20 12:27 UTC, jpodivin requested changes
Please add the new variable into argspec.

2023-09-20 12:45 UTC, booxter requested changes

2023-09-20 13:19 UTC, slawqo commented on roles/edpm_neutron_sriov/tasks/configure.yml
> +    - name: discover secrets in {{ edpm_neutron_sriov_config_src }}
Done

2023-09-20 13:19 UTC, slawqo commented
> Please add the new variable into argspec.

done

2023-09-20 13:55 UTC, booxter commented
/lgtm

2023-09-20 19:41 UTC, booxter commented
```
        "TASK [edpm_neutron_sriov : discover secrets in /var/lib/openstack/configs/neutron-sriov] ***",
Warning: [WARNING]: Skipped '/var/lib/openstack/configs/neutron-sriov' path due to this",
        "access issue: '/var/lib/openstack/configs/neutron-sriov' is not a directory",
        "ok: [fake-sriov-compute-1 -> localhost]",
```

2023-09-21 09:00 UTC, slawqo commented
recheck

> ```
>         "TASK [edpm_neutron_sriov : discover secrets in /var/lib/openstack/configs/neutron-sriov] ***",
> Warning: [WARNING]: Skipped '/var/lib/openstack/configs/neutron-sriov' path due to this",
>         "access issue: '/var/lib/openstack/configs/neutron-sriov' is not a directory",
>         "ok: [fake-sriov-compute-1 -> localhost]",
> ```

isn't it like that because there is no actually /var/lib/openstack/configs/neutron-sriov there during the molecule test?

2023-09-21 14:14 UTC, booxter commented
OK I know the reason why your config file with transport_url was not properly loaded. You need this fix to point molecule to the directory with the config that mimics the one from Secret prepared by neutron-operator:

```
diff --git a/roles/edpm_neutron_sriov/molecule/default/converge.yml b/roles/edpm_neutron_sriov/molecule/default/converge.yml
index 08d27ef..5746332 100644
--- a/roles/edpm_neutron_sriov/molecule/default/converge.yml
+++ b/roles/edpm_neutron_sriov/molecule/default/converge.yml
@@ -19,4 +19,4 @@
   roles:
     - role: "edpm_neutron_sriov"
       vars:
-        edpm_ovn_config_src: "{{lookup('env', 'MOLECULE_SCENARIO_DIRECTORY')}}/test-data"
+        edpm_neutron_sriov_agent_config_src: "{{lookup('env', 'MOLECULE_SCENARIO_DIRECTORY')}}/test-data"
```

With that, you should be able to:

1. revert the patch that moves log-file from config file to command.
2. revert the switch from neutron.conf.d to /etc/neutron/conf.d path.

2023-09-21 14:16 UTC, booxter requested changes
Please fix roles/edpm_neutron_sriov/molecule/default/converge.yml to point to the right test-data path. Then revert the switch to /etc/neutron/conf.d and the move of the log-dir.

2023-09-21 14:38 UTC, slawqo commented
> Please fix roles/edpm_neutron_sriov/molecule/default/converge.yml to point to the right test-data path. Then revert the switch to /etc/neutron/conf.d and the move of the log-dir.

Done, thx a lot :)

2023-09-21 14:56 UTC, booxter commented
/lgtm

2023-09-21 16:13 UTC, booxter commented
```
error: unable to default to a user name: the server is currently unable to handle the request (get users.user.openshift.io ~)
```

2023-09-21 16:13 UTC, booxter commented
recheck

2023-09-22 05:16 UTC, slawqo commented
recheck

2023-09-22 06:27 UTC, karelyatin approved these changes
/lgtm

2023-09-22 07:49 UTC, Sandeepyadav93 commented
recheck

2023-09-22 12:15 UTC, slawqo commented
recheck

2023-09-22 13:45 UTC, booxter commented
recheck

2023-09-22 15:09 UTC, merged