SR-IOV is not configured when the provider is not set
openstack-k8s-operators/edpm-ansible pull request #360
Opened 2023-09-21 09:08 UTC by Jaganathancse

The default provider still remains as 'ifcfg' and when its not specified, the SR-IOV PF configuration is skipped. Adding the changes to support the same.

2023-09-21 09:13 UTC, karthiksundaravel reviewed
LGTM ! Thanks

2023-09-21 12:54 UTC, rebtoor commented
recheck

2023-09-21 12:55 UTC, rebtoor requested changes

2023-09-21 12:55 UTC, rebtoor commented on plugins/modules/edpm_os_net_config.py
> +    else
there's a missing colon

2023-09-22 05:17 UTC, slawqo commented
/lgtm

2023-09-28 04:55 UTC, Jaganathancse commented
/recheck

2023-09-28 20:15 UTC, rebtoor approved these changes

2023-09-28 20:16 UTC, rebtoor commented
recheck

there was a 401 error on the cluster (dataplane stuff has been executed so it should not be caused by this PR)

2023-09-28 21:32 UTC, merged