Do not attempt to manage collocated Ceph containers
openstack-k8s-operators/edpm-ansible pull request #364
Opened 2023-09-22 15:45 UTC by fultonj

If an HCI EDPM node has Ceph containers, then they should not be be manged by the edpm_container_manage role. Add a new task to exclude Ceph containers from the list of containers built by the call to
containers.podman.podman_container_info.

Without this new task, the edpm_container_manage role delete_orphan.yml tasks file attempts to process Ceph containers but it cannot handle them so it fails with an AttributeError: 'NoneType' object has no attribute 'get'.

2023-09-22 15:51 UTC, jpodivin requested changes
Great work. The only addition I would recommend is a note in role documentation, explicitly stating that this role skips Ceph containers. Otherwise people may use it for that and wonder why nothing is happening.

2023-09-22 15:51 UTC, jpodivin commented on roles/edpm_container_manage/tasks/delete_orphan.yml
> +- name: Exclude Ceph containers from podman container list
On one hand I'm wondering if this could be done as filter in the followup task. Otoh this is way more readable.

2023-09-22 16:06 UTC, fultonj commented
> Great work. The only addition I would recommend is a note in role documentation, explicitly stating that this role skips Ceph containers. Otherwise people may use it for that and wonder why nothing is happening.

Done.

2023-09-22 16:21 UTC, abays reviewed
+1

This change works for me in my CephHCI environment

2023-09-25 12:31 UTC, jpodivin approved these changes

2023-09-25 12:40 UTC, merged