Add frr and ovn_bgp_agent images to download_cache
openstack-k8s-operators/edpm-ansible pull request #383
Opened 2023-10-02 10:01 UTC by luis5tb

2023-10-02 21:06 UTC, booxter commented
/ok-to-test

2023-10-02 21:06 UTC, booxter commented
/lgtm

2023-10-03 05:30 UTC, luis5tb commented
/test pre-commit-test

2023-10-03 07:41 UTC, jpodivin requested changes
All seems well, but please add new vars into the argspec.

2023-10-03 10:38 UTC, luis5tb commented
> All seems well, but please add new vars into the argspec.

Done

2023-10-03 19:33 UTC, booxter commented
/lgtm

2023-10-04 10:05 UTC, jpodivin approved these changes

2023-10-04 10:14 UTC, merged