Ensure logrotate image is also pre-downloaded
openstack-k8s-operators/edpm-ansible pull request #389
Opened 2023-10-04 09:31 UTC by luis5tb

2023-10-04 09:35 UTC, fao89 commented
/ok-to-test

2023-10-04 10:04 UTC, jpodivin approved these changes

2023-10-04 12:07 UTC, luis5tb commented
still testing this as it is not working as expected

2023-10-04 13:39 UTC, luis5tb commented
now it is working

2023-10-04 13:56 UTC, rebtoor requested changes
edpm_logrotate_crond is already in the download_cache: https://github.com/openstack-k8s-operators/edpm-ansible/pull/338

2023-10-04 14:01 UTC, luis5tb commented
> edpm_logrotate_crond is already in the download_cache: #338

but that is only for the packages, not for the container image

2023-10-04 14:04 UTC, rebtoor commented
> > edpm_logrotate_crond is already in the download_cache: #338
> 
> but that is only for the packages, not for the container image

Oh, sorry, you're right. I'll leave you a review just to change a bit in the download task. (I saw that you already solved the merge issue, thanks!)

2023-10-04 14:10 UTC, rebtoor requested changes

2023-10-04 14:10 UTC, rebtoor commented on roles/edpm_download_cache/tasks/container_images.yml
> +- name: Download images for edpm_logrotate_crond role
We already call download_cache.yml during the download of the packages so this task, as it stands, would be redundant. Do you mind splitting the download_cache in two different task files so we can call them independently?

2023-10-04 14:10 UTC, rebtoor commented on roles/edpm_logrotate_crond/tasks/download_cache.yml
> +  loop:
I think we can avoid to use a loop here since a single image is downloaded.

2023-10-05 08:05 UTC, rebtoor approved these changes

2023-10-05 08:09 UTC, merged