Add molecule test to ovn_bgp_agent component
openstack-k8s-operators/edpm-ansible pull request #485
Opened 2023-11-03 14:59 UTC by fernandoroyosanchez

Add molecule test to ovn_bgp_agent component

2023-11-23 11:23 UTC, fernandoroyosanchez commented
recheck

2023-11-23 16:38 UTC, fernandoroyosanchez commented
recheck

2023-11-30 08:42 UTC, rebtoor commented
/ok-to-test

2023-11-30 08:46 UTC, rebtoor requested changes
You should add this molecule scenario to zuul (see `zuul.d` folder in the root of the repo) to be executed.

2023-11-30 11:35 UTC, luis5tb commented on roles/edpm_ovn_bgp_agent/tasks/configure.yml
> +          - "*ovn-bgp-agent*conf"
this is not needed, please remove

2023-11-30 11:40 UTC, fernandoroyosanchez commented on roles/edpm_ovn_bgp_agent/tasks/run.yml
> +    name: osp.edpm.edpm_container_standalone
done

2023-11-30 11:40 UTC, fernandoroyosanchez commented on roles/edpm_ovn_bgp_agent/tasks/configure.yml
> +          - "*ovn-bgp-agent*conf"
done!

2023-11-30 11:43 UTC, fernandoroyosanchez commented
> You should add this molecule scenario to zuul (see `zuul.d` folder in the root of the repo) to be executed.

already added! thx for the review!!!!

2023-11-30 11:43 UTC, luis5tb commented
/lgtm

2023-11-30 13:35 UTC, merged