cmdline reading issue in kernel args
openstack-k8s-operators/edpm-ansible pull request #486
Opened 2023-11-07 09:12 UTC by Jaganathancse

2023-11-08 12:21 UTC, Jaganathancse commented
/retest

2023-11-15 11:40 UTC, jpodivin requested changes
Could you please point to the issue this is supposed to solve? As it is I have no idea.

2023-11-21 08:19 UTC, jpodivin commented
Ok. Could you please put that in the commit msg?

2023-11-21 10:40 UTC, Jaganathancse commented
> Ok. Could you please put that in the commit msg?
@jpodivin  Done.

2023-11-21 13:08 UTC, merged