Call package update via bootstrap playbook
openstack-k8s-operators/edpm-ansible pull request #530
Opened 2024-01-04 11:24 UTC by raukadah

Currently tempest tests are failing due to old packages installed on edpm node.

Recently we have added https://github.com/openstack-k8s-operators/edpm-ansible/pull/518 to perform DNF update via edpm_bootstrap role.

But bootstrap-openstack-edpm-ipam pod calls bootstrap.yml playbook not the role that's why update_packages playbook is not called leaving old packages on the node.

Calling update_packages.yml playbook via bootstrap.yml playbook updates the packages and fixes the issue.

2024-01-04 17:19 UTC, slagle reviewed
https://github.com/openstack-k8s-operators/edpm-ansible/pull/518 is being reverted in https://github.com/openstack-k8s-operators/edpm-ansible/pull/531

I would prefer to keep the package update as something that is done in CI, or can be enabled from CI by setting an ansible variable. Forcing a package update will break disconnected environments that are using images with pre-installed packages.

2024-01-04 17:19 UTC, slagle commented
> #518 is being reverted in #531
> 
> I would prefer to keep the package update as something that is done in CI, or can be enabled from CI by setting an ansible variable. Forcing a package update will break disconnected environments that are using images with pre-installed packages.

@bogdando FYI

2024-01-08 10:50 UTC, jpodivin reviewed
I would prefer the current way. If the CI is failing due to missing updates we should address the issue in CI, not in the collection.

2024-01-09 15:06 UTC, bogdando commented
FYI https://github.com/openstack-k8s-operators/edpm-ansible/pull/532
@SeanMooney has some better ideas than reverting the subject. So if you could rebase this on top of the above pr 532?

2024-01-10 13:14 UTC, bogdando requested changes
please see my comments above

2024-01-10 13:25 UTC, raukadah commented
recheck

2024-01-10 14:22 UTC, bogdando commented
> > please see my comments above
> 
> Thank you @bogdando for the review, I have added Depends-On: #532 , I think we donot need to rebase it. Zuul will take care of testing it together.

There likely merge conflicts to happen. Also, it could be that #532 already contains this change?

2024-01-17 06:11 UTC, raukadah commented
@bogdando Thank you! I have tested https://github.com/openstack-k8s-operators/edpm-ansible/pull/532 with https://github.com/openstack-k8s-operators/ci-framework/pull/1027 here https://review.rdoproject.org/r/c/testproject/+/51226/2#message-19838ba0d7e193471ac55cfa369f81d7bfc7a477 It fixes the package update issue.

I think we no longer need https://github.com/openstack-k8s-operators/edpm-ansible/pull/530 pr. Hence, closing it.

2024-01-17 06:11 UTC, closed without merging