Add ceilometer config customization
openstack-k8s-operators/edpm-ansible pull request #544
Opened 2024-01-24 10:23 UTC by vyzigold

This lets us customize the ceilometer configuration based on the customServiceConfig field in ceilometer's part of the control plane CR.

Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/285

2024-01-25 07:09 UTC, vyzigold commented
recheck FAILED! => {"msg": "'ctlplane_cidr' is undefined. 'ctlplane_cidr' is undefined"}

Should apparently be fixed in https://github.com/openstack-k8s-operators/openstack-operator/pull/639

2024-01-25 08:50 UTC, vyzigold commented
I'll need to do a few more changes to the ansible to account for a possibility of the custom.conf missing.

/hold

2024-02-02 06:32 UTC, vyzigold commented
recheck

2024-02-02 10:03 UTC, jlarriba requested changes

2024-02-02 10:03 UTC, jlarriba commented on roles/edpm_telemetry/tasks/deploy_ceilometer.yml
> +        "dest": "{{ edpm_ceilometer_config_dest }}/ceilometer/ceilometer-agent-ipmi.json"
it lacks the edpm_telemetry tag

2024-02-02 10:03 UTC, jlarriba commented on roles/edpm_telemetry/tasks/deploy_ceilometer.yml
> +
same as above

2024-02-05 08:33 UTC, jlarriba approved these changes

2024-02-05 12:41 UTC, jlarriba commented
/lgtm

2024-02-12 14:03 UTC, jpodivin approved these changes

2024-02-12 14:14 UTC, merged