Fix file ownership for neutron dhcp and metadata agent
openstack-k8s-operators/edpm-ansible pull request #670
Opened 2024-06-11 01:49 UTC by mtomaska

Installation tasks in the edpm_neutron_dhcp and edpm_neutron_metadata were using `default(lookup('pipe', 'whoami'))` which [by design runs on the ansible controller](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pipe_lookup.html#notes) and not the target host as this tasks intends. 
Replacing with `default(ansible_user)` which is the user that Ansible logs in.

JIRA: [OSPRH-7321](https://issues.redhat.com/browse/OSPRH-7321)

2024-06-11 01:49 UTC, mtomaska commented
/ok-to-test

2024-06-11 04:12 UTC, rabi commented
> @mtomaska: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

You can request the admins in slack to add you to `openstack-k8s-operators` group. @abays can help.

2024-06-11 04:12 UTC, rabi commented
/ok-to-test

2024-06-11 12:11 UTC, bogdando reviewed
lgtm

2024-06-11 20:38 UTC, booxter commented
/lgtm

2024-06-11 20:54 UTC, booxter commented
```
      "msg": "The task includes an option with an undefined variable. The error was: 'ansible_user' is undefined. 'ansible_user' is undefined\n\nThe error appears to be in '/home/runner/.cache/ansible-compat/498985/collections/ansible_collections/osp/edpm/roles/edpm_neutron_metadata/tasks/install.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create persistent directories\n  ^ here\n"

```

2024-06-11 20:54 UTC, booxter requested changes
The molecule converge step fails.

2024-06-14 12:38 UTC, karelyatin commented on roles/edpm_neutron_dhcp/tasks/install.yml
> +    owner: "{{ item.owner | default(ansible_user_id) }}"
I think would be good to do | default(ansible_user) | default(ansible_user_id) instead as suggested in Jira ticket. As ansible_user_id relies on gathered facts and that can change based on become: yes used or not. Molecule test failed as that using local connection and ansible_user is not defined in that case. Having the above should work for molecule too unless and until ansible_user explicitly set there.

2024-06-17 13:40 UTC, booxter commented
/lgtm

2024-06-17 14:14 UTC, slawqo reviewed
/lgtm

2024-06-17 18:01 UTC, booxter commented
recheck

```
    timed out waiting for the condition on pods/community-operators-5f87q
    timed out waiting for the condition on pods/community-operators-7b584
    timed out waiting for the condition on pods/marketplace-operator-69d564865b-cfpkp
    timed out waiting for the condition on pods/redhat-marketplace-wkb7c
    timed out waiting for the condition on pods/redhat-operators-4gdrm
```

2024-06-17 21:41 UTC, merged

2024-06-18 04:38 UTC, karelyatin commented
/lgtm

Thanks let's ensure the changes are picked by ansibleee operator and openstack-operator for release before closing the linked Jira