Change pattern for detecting pre-adopted versus edpm nodes
openstack-k8s-operators/edpm-ansible pull request #696
Opened 2024-07-12 12:55 UTC by ciecierski

Change edpm_reboot_old_tripleo_node_config_dir to check for tripleo files in /var/lib/config-data/puppet-generated instead of /var/lib/config-data. Path /var/lib/config-data is still being used in edpm for storing configs whereas puppet-generated is suppose to be used only in 17/wallaby. This will make sure for greenfield auto mode is back working, but reboot is skipped on tripleo nodes during adoption.

Resolves: [OSPRH-8415](https://issues.redhat.com//browse/OSPRH-8415)

2024-07-12 14:12 UTC, bogdando requested changes
In tripleo-ansible there are still roles that rely on /var/lib/config-data/ansible-generated.

Those might conflict with edpm-ansible, and need to be discovered as "old" ones instead. The only option I see - never use /var/lib/config-data/ansible-generated in edpm-ansible

2024-07-12 14:54 UTC, ciecierski commented
> In tripleo-ansible there are still roles that rely on /var/lib/config-data/ansible-generated.
> 
> Those might conflict with edpm-ansible, and need to be discovered as "old" ones instead. The only option I see - never use /var/lib/config-data/ansible-generated in edpm-ansible

I switched to **/var/lib/config-data/puppet-generated**. This is not used in edpm for 100%.
For ansible-generated true, still some edpm-ansible roles use it and some /var/lib/edpm-config

2024-07-15 08:20 UTC, jpodivin approved these changes
I have only an exceedingly minor nitpick. The documentation should include a note about the pattern for future reference. Other than that this has my +2. Great job!

2024-07-15 08:20 UTC, jpodivin commented on roles/edpm_reboot/molecule/pre-adoption/converge.yml
> +# Copyright 2023 Red Hat, Inc.
s/2023/2024

2024-07-15 10:52 UTC, bogdando commented
> I switched to **/var/lib/config-data/puppet-generated**. This is not used in edpm for 100%.
> For ansible-generated true, still some edpm-ansible roles use it and some /var/lib/edpm-config

OK, this should work as long there would be no /var/lib/config-data/ansible-generated w/o puppet-generated in the legacy environment, and to my knowledge, that is always true. So indeed, we can ignore the fact that /var/lib/config-data/ansible-generated may be used by osp AND rhoso for configs rendering

2024-07-15 10:53 UTC, bogdando approved these changes
/lgtm

2024-07-15 13:00 UTC, jpodivin approved these changes

2024-07-15 13:54 UTC, jistr approved these changes

2024-07-15 19:42 UTC, ciecierski commented
recheck

2024-07-15 23:24 UTC, merged

2024-07-16 10:08 UTC, ciecierski commented
/cherry-pick 18.0.0-proposed