Fix mounting issue for hgpages and test
openstack-k8s-operators/edpm-ansible pull request #711
Opened 2024-07-26 09:41 UTC by mrkisaolamb

2024-07-26 21:23 UTC, slagle commented
/retest

2024-07-26 21:24 UTC, slagle approved these changes

2024-07-29 07:58 UTC, rebtoor requested changes

2024-07-29 07:58 UTC, rebtoor commented on roles/edpm_extra_mounts/molecule/default/verify.yml
> +      with_items: "{{ mount_check.results }}"
```suggestion
    - name: Check if directories are mounted
      ansible.builtin.assert:
        that:
          - "{{ item is mount }}"
        fail_msg: "Directory {{ item }} isn't mounted!"
      loop:
        - "/dev/hugepages1G"
        - "/dev/hugepages2MB"
```

A simpler but elegant solution with a single task using [mount](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/mount_test.html) ansible test.

I tried locally with this playbook:
```
---
- hosts: localhost
  vars:
    mountpoints:
      - /dev/pts
      - /dev/shm
      - /dev/nonexistent
  tasks:
    - name: Check if devices are mounted
      ansible.builtin.assert:
        that:
          - "{{ item is mount }}"
        fail_msg: "Directory {{ item }} isn't mounted!"
      loop: "{{ mountpoints }}"
```

and here's the result:

```
TASK [Check if devices are mounted] **********************************************************************************************************************************************************************************************************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ item is mount }}
ok: [localhost] => (item=/dev/pts) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "/dev/pts",
    "msg": "All assertions passed"
}
ok: [localhost] => (item=/dev/shm) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "/dev/shm",
    "msg": "All assertions passed"
}
failed: [localhost] (item=/dev/nonexistent) => {
    "ansible_loop_var": "item",
    "assertion": "{{ item is mount }}",
    "changed": false,
    "evaluated_to": false,
    "item": "/dev/nonexistent",
    "msg": "Directory /dev/nonexistent isn't mounted!"
}
```

2024-07-29 09:26 UTC, rebtoor approved these changes

2024-07-29 09:31 UTC, rebtoor commented on roles/edpm_extra_mounts/molecule/default/verify.yml
> +      with_items: "{{ mount_check.results }}"
ack, i'll try to understand why, for now we can merge this PR as is. Thanks a lot!

2024-07-29 09:39 UTC, merged

2024-07-29 10:28 UTC, mrkisaolamb commented
/cherry-pick 18.0.0-proposed