Change permission for /etc/rsyslog.d
openstack-k8s-operators/edpm-ansible pull request #775
Opened 2024-10-04 08:29 UTC by mgirgisf

2024-10-04 08:32 UTC, vyzigold commented
/ok-to-test

2024-10-07 07:43 UTC, mgirgisf commented
recheck

2024-10-07 12:21 UTC, jlarriba commented
/lgtm

We need this as we are getting blocked from permissions on that dir on downstream testing.

2024-10-07 12:22 UTC, elfiesmelfie requested changes

2024-10-07 12:22 UTC, elfiesmelfie commented on roles/edpm_telemetry_logging/tasks/configure.yml
> +    - name: Change permissions of /etc/rsyslog.d to 755
```suggestion
    - name: Ensure that /etc/rsyslog.d/ exists with the right permissions
```

2024-10-07 14:18 UTC, elfiesmelfie approved these changes

2024-10-08 07:24 UTC, jpodivin approved these changes

2024-10-08 07:29 UTC, merged