Prevent NM from automatic (DHCP/SLAAC) configuration on ethernet devices
openstack-k8s-operators/edpm-ansible pull request #840
Opened 2024-12-06 11:11 UTC by vcandapp

When edpm_network_config role uses os-net-config to perform host network configuration, duplicate DHCP requests from NM are causing connectivity issue. Eg.

https://issues.redhat.com/browse/OSPRH-9142

This fix prevents NM from configure DHCP by default

This PR duplicates older [PR](https://github.com/openstack-k8s-operators/edpm-ansible/pull/720)

2024-12-10 08:02 UTC, vcandapp commented
recheck

2024-12-18 20:35 UTC, slagle approved these changes

2024-12-23 06:43 UTC, bshephar approved these changes

2024-12-23 06:43 UTC, bshephar commented
recheck

2025-01-03 06:53 UTC, vcandapp commented
recheck

2025-01-03 10:04 UTC, rabi requested changes

2025-01-03 10:04 UTC, rabi commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
Where is `edpm_bootstrap_network_service`  var set or default defined? This var does not exist by default. Also the code does not look correct to me. When  `edpm_bootstrap_network_service` is anything other than 'NetworkManager` os-net-config won't run?

2025-01-04 11:27 UTC, bshephar commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
That variable appears to be set in the bootstrap role:
https://github.com/openstack-k8s-operators/edpm-ansible/blob/main/roles/edpm_bootstrap/defaults/main.yml#L62

So, I assumed they were using it from there.

The same conditional check is also used in the Bootstrap role by the looks of it:
https://github.com/openstack-k8s-operators/edpm-ansible/blob/main/roles/edpm_bootstrap/tasks/bootstrap.yml#L73

I'm not sure of the background for this variable though. Just an observation in response to this comment. Maybe we can take this opportunity to evaluate our use of the variable to ensure it still makes sense.

2025-01-06 08:04 UTC, vcandapp commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
Also the code does not look correct to me. When `edpm_bootstrap_network_service` is anything other than 'NetworkManager` os-net-config won't run?

- os-net-config with ifcfg scripts doesn't have any dependency on NetworkManager.
- But, the reason for adding this check was, if os-net-config is used for deployment and bootstrap used "NetworkManager" during cloud-init, we need to disable the auto dhcp

2025-01-06 08:06 UTC, vcandapp commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
> > So, I assumed they were using it from there.
> 
> That's a role var and it won't be availale for other roles or other playbook runs. Also, every service is run as a separate playbook, so that won't be available in this role. 

@rabi , will referring like this fix it?
- https://github.com/openstack-k8s-operators/edpm-ansible/blob/main/roles/edpm_derive_pci_device_spec/defaults/main.yml#L26
(neutron_sriov_agent default is referred in derive_pci role)

2025-01-06 08:20 UTC, rabi commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
> @rabi , will referring like this fix it?

I'm not sure what you mean by that. This has to have a role default like in bootstrap role or  set as a fact or ansible var when the playbook is called.

2025-01-06 21:12 UTC, slagle commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
The `edpm_bootstrap_network_service` variable doesn't look like it's used correctly even in edpm_bootstrap, as it defaults to NetworkManager, which will then be enabled after installing the `network-scripts` package.

Honestly, this commit looks pretty suspect that changed the default from `network` to `NetworkManager`:

https://github.com/openstack-k8s-operators/edpm-ansible/commit/31b1b0297d8c6f4121bcb9682008647666d3900c

I don't see a compelling reason why we want to enable `NetworkManager` after installing `network-scripts`.

Perhaps we should track this issue down from that angle, b/c it's really the fact that `NetworkManager` is enabled that is the issue.

2025-01-07 05:00 UTC, vcandapp commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
The above commits seems to be related to [Only use the network service for EL 7](https://github.com/openstack-archive/tripleo-ansible/commit/964fa4ddef95bcaa184e81d0565a521aeb7c3975) , since NM is by default enabled >=rhel8

Maybe for now I can safely assume "edpm_bootstrap_network_service" is NetworkManager and remove the check for CI to pass

2025-01-07 05:41 UTC, vcandapp commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
This is the [patch](https://code.engineering.redhat.com/gerrit/c/tripleo-ansible/+/453443) we need to fix for edpm also

2025-01-07 06:55 UTC, rabi commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
> Maybe for now I can safely assume "edpm_bootstrap_network_service" is NetworkManager and remove the check for CI to pass

Can you answer the question @slagle asked? Should we not stop/disable NetworkManager when using network-scripts. I understand that we've been keeping it enabled and running since TripleO days and doing these hacks to prevent it doing it's things, but do we really need it running.

2025-01-07 07:17 UTC, vcandapp commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
@slagle / @rabi, there are few reasons for not disabling NM as of now:
- os-net-config can use nmstate provider in future, which will eventually need NM
- Disabling/stopping NM might need a wider review and QE scope
- The issue we try to fix is the flood of DHCP requests (esp. for SR-IOV VFs) during node provision, which leads to timeout 
- SR-IOV VFs are treated as individual i/f by NM and DHCP requests are sent out for all on their creation

cc @karthiksundaravel DanSneddon for further comments

2025-01-07 10:55 UTC, karthiksundaravel commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
The network-scripts has a variable NM_CONTROLLED, which could be used to enable or disable NetworkManager for that interface. All we need now is to prevent NM from configuring the devices which are not configured or yet to be configured by network scripts. Given this requirement, setting no-auto-default=* does the job well.  This configuration should hold good irrespective of the os-net-config provider (ifcfg or nmstate) as well.

2025-01-07 17:53 UTC, vcandapp commented
recheck

2025-01-08 09:59 UTC, dsneddon commented
As @vcandapp mentioned NM will cause duplicate DHCP requests, so this fix will prevent NM from automatically creating DHCP requests when they are not needed. This will improve the behavior that we see and ensure that NM is operating in a way that does not conflict with os-net-config. It is understandable that NM would create DHCP enabled configurations by default for interfaces for normal use cases, but for cloud we really need for it to get out of the way and let the automation work as designed.

2025-01-08 10:05 UTC, dsneddon commented on roles/edpm_network_config/tasks/main.yml
> +  when: ( edpm_bootstrap_network_service == 'NetworkManager' ) and
Yes, I agree with the comments from @karthiksundaravel and we already have seen this causing issues in the field. The only way to be sure that things behave as expected is for auto-default to be turned off in the configuration as it isn't needed for this use case anyway (cloud-init will do what is required, but NM doesn't need to step in and create configurations for unconfigured interfaces).

2025-01-08 16:54 UTC, vcandapp commented
recheck

2025-01-10 06:17 UTC, rabi reviewed
+2 I'm fine with the current change.

2025-01-10 07:04 UTC, rabi commented
+2

2025-01-10 07:34 UTC, vcandapp commented
receck

2025-01-17 11:44 UTC, slagle approved these changes

2025-01-17 11:48 UTC, merged

2025-01-22 10:41 UTC, vcandapp commented
/cherry-pick 18.0-fr1